@startuml
'https://plantuml.com/sequence-diagram

class Event
class conference
class boardmeeting
Event <|-- conference
Event <|-- boardmeeting

class person
class member
class boardmember
person <|-- member
member <|-- boardmember
class AAUOC
class location
AAUOC <|-- location
location -- Event
Event -- member
conference -- person
AAUOC <|-- person
@enduml