@startuml
'https://plantuml.com/sequence-diagram

class Event{
date: Date
description: String
assign(I: Location) : void
}
class conference{
max_attendees : Integer
}
class boardmeeting
Event <|-- "0..*" conference
Event <|-- "0..*" boardmeeting

class person{
name: String
}
class member{
e-mail: String
}
class boardmember
person <|-- "0..*" member
member <|-- "0..*" boardmember
class AAUOC{
newLocation(I: Location): void
newPerson(p: Person) : void
newEvent(e: Event) : void register(m: Member,e: Event) : void
informEvent(e: Event) : void
}
class location{
description: String
address: String
}
AAUOC <|-- "0..*" location
location -- Event
AAUOC <|-- "0..*" Event
Event -- member
conference -- person
AAUOC <|-- "0..*" person
@enduml